version: "3"
services: 
  portainer:
    image: "portainer/portainer:1.20.2"
    container_name: "portainer"
    restart: "always"
    ports: 
      - "9000:9000"
    volumes: 
      - "portainer_data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes: 
  portainer_data:
